[docker_mariadb_server]
mariadb_isard1 ansible_host=172.20.25.84
mariadb_isard2 ansible_host=172.20.25.83 ansible_user=isard
mariadb ansible_host=172.20.16.203 ansible_user=usuari_server



[docker_python3]
python3_isard ansible_host=172.20.25.84 ansible_user=isard
python3_serverBBDD ansible_host=172.20.24.214
python3_serverIA ansible_host=172.20.16.203


[webmin_server]
webmin ansible_host=172.20.25.84 ansible_user=isard
webmin_serverBBDD ansible_host=172.20.24.214
webmin_serverIA ansible_host=172.20.16.203

[jupyterhub]
jupyterhub ansible_host=172.20.25.84
jupyterhub_IA ansible_host=172.20.16.203

[jupyterhub:vars]
ansible_user=dcs
ansible_group=docker
imagenes_path=/var/Images
dir_permissions=775
file_permissions=664

[Servidores_isard]
server1_isard ansible_host=172.20.25.83 ansible_user=isard
server2_isard ansible_host=172.20.25.84 ansible_user=isard
server3_isard ansible_host=172.20.25.78 ansible_user=isard
server2_BBDD ansible_host=172.20.24.214
server3_IA ansible_host=172.20.16.203

[elastic]
server_elastic ansible_host=172.20.16.203 ansible_user=dcs