[docker_mariadb_server]
mariadb_dcsBBDD ansible_host=172.18.6.58 ansible_user=dcs

[docker_python3]
python_dcsBBDD ansible_host=172.20.18.6.58 ansible_user=dcs

[webmin_server]
webmin_serverIA ansible_host=172.20.18.6.59

[jupyterhub]
server_jupyterhub ansible_host=172.20.16.6.59 ansible_user=dcs

[jupyterhub:vars]
ansible_user=dcs
ansible_group=docker
imagenes_path=/var/Images
dir_permissions=775
file_permissions=664


[elastic]
server_elasticBBDD ansible_host=172.20.18.6.58 ansible_user=dcs

[mirthconnect]
server_mirth ansible_host=172.20.18.6.58 ansible_user=dcs

