---
- name: Instalación de Docker y MariaDB en Docker
  hosts: mariadb
  become: true
  vars_files:
    - secret_password.yml
  tasks:
    - name: Instalar dependencias necesarias
      apt:
        name:
          - lsb-release
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - curl
        state: present
        update_cache: yes

    - name: Instalar Docker y Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Crear directorio para MariaDB
      file:
        path: /srv/mariadb
        state: directory
        mode: '0755'

    - name: Pull de la imagen de MariaDB
      docker_image:
        name: mariadb:latest
        source: pull

    - name: Crear volumen para MariaDB
      docker_volume:
        name: ohv
        state: present

    - name: Copiar my.cnf
      copy:
        src: ./my.cnf
        dest: /srv/mariadb/my.cnf
        mode: '0755'

    - name: Copiar docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /srv/mariadb/docker-compose.yml
        mode: '0755'

    - name: Ejecutar docker-compose up -d
      command: docker compose up -d
      args:
        chdir: /srv/mariadb

    - name: Crear script para instalación dentro del contenedor
      copy:
        content: |
          #!/bin/bash
          docker exec -it openhospital_db bash
          apt update && apt install -y wget unzip
          wget OpenHospital-v1.14.2-multiarch-client.zip https://github.com/informatici/openhospital/releases/download/v1.14.2/OpenHospital-v1.14.2-multiarch-client.zip
          unzip OpenHospital-v1.14.2-multiarch-client.zip
        dest: /srv/mariadb/setup_openhospital.sh
        mode: '0755'

    - name: Copiar script dentro del contenedor
      command: sudo docker cp /srv/mariadb/setup_openhospital.sh openhospital_db:/setup_openhospital.sh

    - name: Ejecutar script dentro del contenedor
      command: sudo docker exec -it openhospital_db bash /setup_openhospital.sh
