---
- name: Instalar Elasticsearch y Kibana con Docker
  hosts: server_elasticBBDD
  become: true
  tasks:
    - name: Configurar DNS en /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "{{ item }}"
        state: present
      loop:
        - "nameserver 8.8.8.8"
        - "nameserver 1.1.1.1"

    - name: Instalar dependencias
      apt:
        name:
          - docker.io
          - wget
        state: present
        update_cache: yes

    - name: Iniciar y habilitar el servicio Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Crear red de Docker para Elastic Stack si no existe
      command: docker network create elastic
      ignore_errors: yes

    - name: Descargar y ejecutar Elasticsearch con autenticación
      command: >
        docker run --name es01 -p 9200:9200 -d docker.elastic.co/elasticsearch/elasticsearch:9.0.0

    - name: Esperar a que Elasticsearch esté listo
      wait_for:
        host: localhost
        port: 9200
        delay: 10
        timeout: 60

    - name: Configurar DNS en /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "{{ item }}"
        state: present
      loop:
        - "nameserver 8.8.8.8"
        - "nameserver 1.1.1.1"
        
    - name: Descargar y ejecutar Kibana
      command: >
        docker run --name kib01 -p 5601:5601 -d docker.elastic.co/kibana/kibana:9.0.0
