---
- name: Instalación de Python 3
  hosts: all
  become: yes
  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar Python 3
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Verificar la instalación de Python 3
      command: python3 --version
