version: '3.8'

services:
  jupyterhub:
    image: jupyterhub/jupyterhub:latest
    container_name: jupyterhub
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "/srv/jupyterhub/data:/srv/jupyterhub"
      - "/srv/jupyterhub/ssl:/etc/ssl/jupyterhub"
    environment:
      - JUPYTERHUB_CRYPT_KEY=${JUPYTERHUB_CRYPT_KEY}
    command: >
      jupyterhub --ip 0.0.0.0 --port 8000 
      --ssl-key=/etc/ssl/jupyterhub/servidor.key 
      --ssl-cert=/etc/ssl/jupyterhub/servidor.crt 
      --config /srv/jupyterhub/jupyterhub_config.py
    networks:
      - jupyterhub-net

networks:
  jupyterhub-net:
    driver: bridge
