---
- name: Desplegar JupyterHub amb Docker
  hosts: jupyterhub
  become: true
  tasks:
    - name: Instalar Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Instalar Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Crear directorio para JupyterHub
      file:
        path: /srv/jupyterhub
        state: directory
        mode: 0755

    - name: Copiar Dockerfile
      copy:
          src: Dockerfile
          dest: /srv/jupyterhub/Dockerfile

    - name: Copiar script de creacion de jupyterhub
      copy:
        src: cargar_jupyterhub.sh
        dest: /srv/jupyterhub/cargar_jupyterhub.sh
        mode: 0755

    - name: Copiar script de Eliminar_comentarios.sh
      copy:
        src: Eliminar_comentarios.sh
        dest: /srv/jupyterhub/Eliminar_comentarios.sh
        mode: 0755

    - name: Construir imatge de JupyterHub
      shell: docker build -t jupyterhub .
      args:
        chdir: /srv/jupyterhub

    - name: Ejecutar contenedor de JupyterHub
      shell: >
        docker run -d --name jupyterhub 
        -p 8000:8000 
        -v /srv/jupyterhub:/srv/jupyterhub 
        jupyterhub

    - name: Copiar script para eliminar comentarios
      command: docker cp remove_comments.sh jupyterhub:/srv/jupyterhub/Eliminar_comentarios.sh

    - name: Cargar script de creacion de jupyterhub
      copy:
        src: cargar_jupyterhub.sh
        dest: /srv/jupyterhub/cargar_jupyterhub.sh
        mode: 0755

    - name: Ejecutar script de creacion de jupyterhub
      shell: bash /srv/jupyterhub/cargar_jupyterhub.sh
