---
- name: Desplegar JupyterHub amb Docker
  hosts: jupyterhub
  become: true
  tasks:
    - name: Instalar Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Instalar Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Crear directorio para JupyterHub
      file:
        path: /srv/jupyterhub
        state: directory
        mode: 0755

    - name: Copiar Dockerfile
      copy:
          src: Dockerfile
          dest: /srv/jupyterhub/Dockerfile

    - name: Construir imatge de JupyterHub
      shell: docker build -t jupyterhub /srv/jupyterhub
      args:
        chdir: /srv/jupyterhub

    - name: Cargar script de creacion de jupyterhub
      copy:
        src: cargar_jupyterhub.sh
        dest: /srv/jupyterhub/cargar_jupyterhub.sh

    - name: Ejecutar script de creacion de jupyterhub
      shell: bash /srv/jupyterhub/cargar_jupyterhub.sh