---
- name: Desplegar JupyterHub con Docker
  hosts: jupyterhub
  become: true
  tasks:
    - name: Instalar Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Instalar Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Crear directorio para JupyterHub
      file:
        path: /srv/jupyterhub
        state: directory
        mode: '0755'

    - name: Copiar Dockerfile
      copy:
        src: Dockerfile
        dest: /srv/jupyterhub/Dockerfile

    - name: Copiar script de creación de JupyterHub
      copy:
        src: cargar_jupyterhub.sh
        dest: /srv/jupyterhub/cargar_jupyterhub.sh
        mode: '0755'

    - name: Copiar script para eliminar comentarios
      copy:
        src: Eliminar_comentarios.sh
        dest: /srv/jupyterhub/Eliminar_comentarios.sh
        mode: '0755'

    - name: Construir imagen de JupyterHub
      command:
        cmd: docker build -t jupyterhub .
        chdir: /srv/jupyterhub

    - name: Ejecutar contenedor de JupyterHub
      docker_container:
        name: jupyterhub
        image: jupyterhub
        state: started
        restart_policy: always
        exposed_ports:
          - "8010:8000"
        volumes:
          - /srv/jupyterhub:/srv/jupyterhub

    - name: Generar configuración de JupyterHub dentro del contenedor
      docker_exec:
        container: jupyterhub
        command: jupyterhub --generate-config

    - name: Ejecutar script para eliminar comentarios dentro del contenedor
      docker_exec:
        container: jupyterhub
        command: bash /srv/jupyterhub/Eliminar_comentarios.sh

    - name: Crear usuario admin con contraseña ciber25
      docker_exec:
        container: jupyterhub
        command: useradd -m -s /bin/bash -p "$(openssl passwd -1 ciber25)" -G sudo admin

    - name: Copiar script de creación de JupyterHub nuevamente
      copy:
        src: cargar_jupyterhub.sh
        dest: /srv/jupyterhub/cargar_jupyterhub.sh
        mode: '0755'

    - name: Ejecutar script de creación de JupyterHub
      shell: bash /srv/jupyterhub/cargar_jupyterhub.sh

    - name: Generar certificado SSL dentro del contenedor
      docker_exec:
        container: jupyterhub
        command: >
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /srv/jupyterhub/jupyterhub.key -out /srv/jupyterhub/jupyterhub.crt
          -subj "/C=US/ST=State/L=City/O=Company/CN=yourdomain.com"
