- name: Distribuir clave SSH a hosts remotos
  hosts: server2_isard
  become: true
  become_user: root

  vars_files:
    - "default.yaml"  # Asegúrate de que esta ruta sea correcta

  tasks:
    - name: Asegurarse de que el paquete OpenSSH esté instalado
      package:
        name: openssh-server
        state: present

    - name: Verificar si ya existe la clave privada SSH
      stat:
        path: "/home/{{ created_username }}/.ssh/id_ed25519"
      register: ssh_key_stat

    - name: Copiar la clave pública SSH al nodo remoto
      ansible.posix.authorized_key:
        user: "{{ created_username }}"
        state: present
        key: "{{ copy_local_key }}"
      when: ssh_key_stat.stat.exists
