---
- name: Instalación de Docker y MariaDB en Docker
  hosts: mariadb
  become: true
  tasks:
    - name: Actualizar paquetes e instalar dependencias
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Instalar Docker y Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Iniciar el servicio Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verificar que Docker esté corriendo
      command: docker ps
      register: docker_status
      failed_when: docker_status.rc != 0
      changed_when: false

    - name: Crear directorio para MariaDB
      file:
        path: /srv/mariadb
        state: directory
        mode: '0755'

    - name: Pull de la imagen de MariaDB
      docker_image:
        name: mariadb:latest
        source: pull

    - name: Crear volumen para MariaDB
      docker_volume:
        name: ohv
        state: present

    - name: Copiar docker-compose.yml
      copy:
        src: ./my.cnf
        dest: /srv/mariadb/my.cnf
        mode: '0755'

    - name: Copiar docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /srv/mariadb/docker-compose.yml
        mode: '0755'

    - name: Ejecutar docker-compose up -d
      command: docker-compose up -d
      args:
        chdir: /srv/mariadb
