version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: openhospital_db
    environment:
      MYSQL_ROOT_PASSWORD: "{{ user_password }}"
      MYSQL_DATABASE: oh
      MYSQL_USER: isf
      MYSQL_PASSWORD: "{{ user_password }}"
    volumes:
      - ohv:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf  # Monta el teu fitxer my.cnf
    ports:
      - "3306:3306"
    networks:
      - oh_network
    restart: unless-stopped

  openhospital_backend:
    image: openjdk:11-jre-slim
    container_name: openhospital_backend
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: oh
      DB_USER: isf
      DB_PASSWORD: "{{ user_password }}"
    networks:
      - oh_network
    command: >
      /bin/bash -c "
      apt update &&
      apt install -y wget unzip nano &&
      mkdir -p /OH &&
      wget https://github.com/informatici/openhospital/releases/download/v1.14.2/OpenHospital-v1.14.2-multiarch-server.zip -O /OH/OpenHospital-v1.14.2-multiarch-server.zip &&
      unzip /OH/OpenHospital-v1.14.2-multiarch-server.zip -d /OH/
      "

volumes:
  ohv:
    external: true

networks:
  oh_network:
    driver: bridge
