---
- name: Instalacion de Docker i Mariadb en docker
  hosts: mariadb
  become: true
  tasks:
        - name: Instalacion de Docker
          apt:
            name: docker.io
            state: present
            update_cache: yes

        - name: Instalacion de Docker Compose
          apt:
            name: docker-compose
            state: present
            update_cache: yes

        - name: Crear directorio para MariaDB
          file:
            path: /srv/mariadb
            state: directory
            mode: 0755

        - name: Copiar Dockerfile
          copy:
              src: Dockerfile
              dest: /srv/mariadb/Dockerfile

        - name: Pull de la imagen de MariaDB
          shell: docker pull mariadb

        - name: Hacer run del Dockerfile
          shell: docker build -t mariadb /srv/mariadb
          args:
            chdir: /srv/mariadb







