- name: Instalación de MariaDB en Docker
  hosts: mariadb_server
  become: true
  tasks:
    - name: Instalar Docker y Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Asegurar que el servicio Docker está en ejecución
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Crear directorio para MariaDB
      file:
        path: /srv/mariadb
        state: directory
        mode: '0755'

    - name: Copiar Dockerfile
      copy:
        src: Dockerfile
        dest: /srv/mariadb/Dockerfile
        mode: '0644'


    - name: Esperar a que MariaDB esté disponible
      wait_for:
        port: 3306
        host: "localhost"
        delay: 5
        timeout: 30

    - name: Mostrar la URL de acceso a MariaDB
      debug:
        msg: "Accede a MariaDB en mysql://{{ ansible_host }}:3306 con el usuario root y la contraseña que has definido"
