---
- name: Instalacion de Docker i Mariadb en docker
  hosts: mariadb
  become: true
  tasks:
        - name: Instalacion de Docker
          apt:
            name: docker.io
            state: present
            update_cache: yes

        - name: Instalacion de Docker Compose
          apt:
            name: docker-compose
            state: present
            update_cache: yes

        - name: Instalacion de Docker Compose plugin
          apt:
            name: docker-compose-plugin
            state: present
            update_cache: yes

        - name: Crear directorio para MariaDB
          file:
            path: /srv/mariadb
            state: directory
            mode: 0755

        - name: Copiar Docker Compose
          copy:
              src: docker-compose.yml
              dest: /srv/mariadb/docker-compose.yml

        - name: Pull de la imagen de MariaDB
          shell: docker pull mariadb

        - name: Pull de la imagen de Apache2
          shell: docker pull apache2

        - name: Hacer run del docker-compose
          shell: docker-compose -f /srv/mariadb/docker-compose.yml up -d
          args:
            chdir: /srv/mariadb

        - name: Cargar script de creacion de base de datos
          copy:
              src: cargar_esquema.sh
              dest: /srv/mariadb/cargar_esquema.sh

        - name: Ejecutar script de creacion de base de datos
          shell: bash /srv/mariadb/cargar_esquema.sh







