---
- name: Configurar JupyterHub amb Docker
  hosts: server_jupyterhubIA
  become: yes
  tasks:
    - name: Instalar dependències necessàries
      apt:
        name:
          - docker.io
          - docker-compose
          - python3-pip
        state: present
        update_cache: yes

    - name: Afegir usuari al grup Docker
      user:
        name: "{{ ansible_user }}"
        groups: "{{ ansible_group }}"
        append: yes

    - name: Reiniciar Docker per aplicar canvis
      systemd:
        name: docker
        state: restarted
      when: ansible_facts['os_family'] == "Debian"

    - name: Crear directori per JupyterHub
      file:
        path: /srv/jupyterhub
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: '0775'

    - name: Copiar Dockerfile al servidor
      copy:
        src: Dockerfile
        dest: /srv/jupyterhub/Dockerfile
        mode: '0644'

    - name: Crear el directori /var/Images al servidor si no existeix
      file:
        path: /var/Images
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_group }}"
        mode: '0775'

    - name: Asegurar permisos correctos para /var/Images y sus subdirectorios
      shell: |
        find {{ imagenes_path }} -type d -exec chmod {{ dir_permissions }} {} \;
        find {{ imagenes_path }} -type f -exec chmod {{ file_permissions }} {} \;
        chown -R {{ ansible_user }}:{{ ansible_group }} {{ imagenes_path }}

    - name: Copiar Imatges locals al directori del servidor
      copy:
        src: Imatges/
        dest: /var/Images/
        owner: root
        group: root
        mode: '0755'
      become: yes

    - name: Copiar jupyterhub_config.py al servidor
      copy:
        src: jupyterhub_config.py
        dest: /srv/jupyterhub/jupyterhub_config.py
        mode: '0644'


    - name: Configurar DNS en /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "{{ item }}"
        state: present
      loop:
        - "nameserver 8.8.8.8"
        - "nameserver 1.1.1.1"

    - name: Construir la imatge Docker de JupyterHub
      community.docker.docker_image:
        name: jupyterhub_custom
        build:
          path: /srv/jupyterhub
        source: build

    - name: Executar el contenidor de JupyterHub amb volums correctes
      community.docker.docker_container:
        name: jupyterhub
        image: jupyterhub_custom
        state: started
        restart_policy: always
        privileged: yes
        ports:
          - "8000:8000"
        volumes:
          - /var/Images:/var/Images
          - /var/Raw:/var/Raw
          - /var/Visualization:/var/Visualization
          - /etc/passwd:/etc/passwd:ro
          - /etc/shadow:/etc/shadow:ro
          - /etc/group:/etc/group:ro
          - /home:/home
          - dacibersalut/Servidor_IA/Instalación_Jupyterhub/dicom_share.sh:/etc/profile.d/dicom_share.sh

    - name: Generar fitxer de configuració de Jupyter Notebook dins del contenidor
      command: "echo 'n' | jupyter-notebook --generate-config"
      become: yes
      become_user: root


    - name: Crear enllaç simbòlic dins del contenidor
      community.docker.docker_container_exec:
        container: jupyterhub
        command: ln -s /var/Images/IMAGENES /etc/skel/Imatges
        user: root

    - name: Crear el directori .jupyter dins del contenidor si no existeix
      community.docker.docker_container_exec:
        container: jupyterhub
        command: mkdir -p /srv/jupyterhub/.jupyter
        user: root

    - name: Crear el fitxer jupyter_notebook_config.py si no existeix
      community.docker.docker_container_exec:
        container: jupyterhub
        command: touch /srv/jupyterhub/.jupyter/jupyter_notebook_config.py
        user: root

    - name: Configurar Jupyter Notebook dins del contenidor per permetre arxius ocults
      community.docker.docker_container_exec:
        container: jupyterhub
        command: echo "c.FileContentsManager.allow_hidden = True" >> /srv/jupyterhub/.jupyter/jupyter_notebook_config.py
        user: root

    - name: Instal·lar llibreria pydicom
      community.docker.docker_container_exec:
        container: jupyterhub
        command: pip install pydicom
        user: root

    - name: Instal·lar llibreria tensorflow
      community.docker.docker_container_exec:
        container: jupyterhub
        command: pip install tensorflow
        user: root
