---
- name: Configurar JupyterHub con Docker
  hosts: all
  become: yes
  tasks:
    - name: Instalar dependencias necesarias
      apt:
        name:
          - docker.io
          - docker-compose
          - python3-pip
        state: present
        update_cache: yes

    - name: Crear directorio para JupyterHub
      file:
        path: /srv/jupyterhub
        state: directory
        mode: '0755'

    - name: Copiar Dockerfile al servidor
      copy:
        src: Dockerfile
        dest: /srv/jupyterhub/Dockerfile

    - name: Construir la imagen Docker
      docker_image:
        name: jupyterhub-custom
        build:
          path: /srv/jupyterhub
        source: build

    - name: Ejecutar el contenedor de JupyterHub
      docker_container:
        name: jupyterhub
        image: jupyterhub-custom
        state: started
        ports:
          - "8000:8000"
        volumes:
          - /srv/jupyterhub:/srv/jupyterhub
