---
- name: Instalación de Python 3 y dependencias necesarias
  hosts: all
  become: yes
  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar Python 3 y paquetes necesarios
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Instalar dependencias de Python (mysql-connector-python, python-dotenv)
      pip:
        name:
          - mysql-connector-python
          - python-dotenv
        state: present

    - name: Verificar la instalación de Python 3
      command: python3 --version
