- name: Instalación de Docker y MariaDB en Docker
  hosts: mariadb_isard
  become: true
  vars_files:
    - vault_secrets.yml  # Archivo encriptado con Ansible Vault
  tasks:
    - name: Instalar dependencias necesarias
      apt:
        name:
          - lsb-release
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - curl
        state: present
        update_cache: yes

    - name: Instalar Docker y Docker Compose
      apt:
        name:
          - docker.io
          - containerd
          - docker-compose
        state: present

    - name: Iniciar el servicio Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Crear directorio para MariaDB
      file:
        path: /srv/mariadb
        state: directory
        mode: '0755'

    - name: Crear archivo .env con credenciales
      copy:
        dest: /srv/mariadb/.env
        content: |
          MYSQL_ROOT_PASSWORD={{ MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE={{ MYSQL_DATABASE }}
          MYSQL_USER={{ MYSQL_USER }}
          MYSQL_PASSWORD={{ MYSQL_PASSWORD }}

          DB_PASSWORD={{ DB_PASSWORD }}
          DB_PORT=3306
        mode: '0600'

    - name: Copiar archivo my.cnf
      copy:
        src: templates/my.cnf
        dest: /srv/mariadb/my.cnf
        mode: '0755'

    - name: Copiar docker-compose.yml
      copy:
        src: templates/docker-compose_template.yml
        dest: /srv/mariadb/docker-compose.yml
        mode: '0755'

    - name: Crear volumen externo para MariaDB
      command: docker volume create ohv

    - name: Ejecutar docker-compose up -d
      command: docker-compose --env-file /srv/mariadb/.env up -d
      args:
        chdir: /srv/mariadb
